name: "Terraform Plan with checkov and fmt"

on:
  workflow_dispatch :
    branches:
      - main


jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v3 
    

  
      - name: Configure AWS credentials
        uses:  aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::038774803581:role/github.to.aws.oicd@
          aws-region: eu-west-2

      
      
      - name: Install Terraform 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest 

      

      - name: Create S3 for Terraform State
        run: |
          aws s3api create-bucket \
          --bucket mubashir-tf-state-bucket-20-11-2025 \
          --region eu-west-2 \
          --create-bucket-configuration LocationConstraint=eu-west-2 || echo "Bucket created"

      
      - name: Wait for S3 provision
        run: sleep 10


      - name: Terraform Init
        working-directory: ./Terraform
        run: terraform init

      - name: Terraform validate
        working-directory: ./Terraform
        run: terraform validate

      - name: Terraform fmt
        working-directory: ./Terraform
        run: terraform fmt -check 

      - name: Checkov Scan
        working-directory: ./Terraform
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
        run: checkov -d .

      - name: Terraform Plan
        working-directory: ./Terraform
        run: terraform plan 



      





    
      


