name: Build and Push Docker Image to ECR with Trivy

on:
  workflow_dispatch :
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest


    permissions:
      id-token: write
      contents: read 

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

# Configure AWS credentials using OIDC

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::038774803581:role/github.to.aws.oicd@
        aws-region: eu-west-2

## Login to ECR

    - name: Login to Amazon ECR
      id: login-ecr 
      uses: aws-actions/amazon-ecr-login@v1

#Build and push Docker image as 'latest'

    - name: Build and push Docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: threat-composer-app
        aws-region: eu-west-2
      run: |
        docker build -t $REGISTRY/$REPOSITORY:latest .

#Running Trivy here to spot errors with Docker image

    - name: Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-actions@0.28.0
      with:
        image-ref: ${{ steps.login-ecr.outputs.registry }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

# If Trivy passed, push image     

    - name: Push Docker Image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}/threat-composer-app:latest
        REPOSITORY: threat-composer-app
      run: |
        docker push $REGISTRY/$REPOSITORY:latest

